// Modules generated by the writing plugin (./build.ts) from content/writing/*.md.

declare module "virtual:writing" {
  export type PostMeta = {
    slug: string;
    title: string;
    /** YYYY-MM-DD */
    date: string;
    description: string;
    /** The description as one short paragraph. */
    dek: string;
    series?: string;
  };
  /** Newest first. */
  export const POSTS: PostMeta[];
  /** One chunk per post. */
  export const LOAD: Record<string, () => Promise<{ html: string }>>;
}
