// How each project is presented on this site, beyond what the API carries: a thumbnail
// for the list (all 16:10, 560x350), the colour it glows on hover, one plain line, and
// for earlier projects the media at the top of their page.

import aussiesPoster from "./assets/aussies-poster.webp";
import aussiesThumb from "./assets/aussies-thumb.webp";
import diesThumb from "./assets/dies-thumb.webp";
import ltThumb from "./assets/lt-thumb.webp";
import mazeThumb from "./assets/maze-thumb.webp";
import sonarThumb from "./assets/sonar-thumb.webp";
import thinking from "./assets/thinking.webp";
import thinkingThumb from "./assets/thinking-thumb.webp";

/** A list thumbnail: an image, a line of terminal text drawn in HTML, or just a name. */
export type Thumb = { src: string } | { term: string } | { name: string };

export type Media =
  | { kind: "video"; src: string; poster: string; width: number; height: number }
  | { kind: "youtube"; id: string }
  | { kind: "image"; src: string; width: number; height: number; alt: string }
  | { kind: "code"; text: string };

export type Look = { thumb: Thumb; glow: string; line?: string; media?: Media };

/** Flagships: their pages are hand-built, so only the list needs anything here. */
export const FLAGSHIP_LOOK: Record<string, Look> = {
  "learning-taichi": { thumb: { src: ltThumb }, glow: "#3f8fd2" },
  "sonar-inverse-rendering": { thumb: { src: sonarThumb }, glow: "#d99a45" },
};

export const EARLIER: Record<string, Look> = {
  "rapid-hi-res-diffusion-latent-space-traversal": {
    line: "Real-time traversal of Stable Diffusion’s latent space at 4K, about 30 fps, on one local machine.",
    thumb: { src: aussiesThumb },
    glow: "#e07a3c",
    media: {
      kind: "video",
      src: "/projects/aussies.mp4",
      poster: aussiesPoster,
      width: 960,
      height: 540,
    },
  },
  "thinking-machine-llm": {
    line: "A language model fine-tuned on a few hundred sentences of one person’s stream of consciousness.",
    thumb: { src: thinkingThumb },
    glow: "#d9d4ca",
    media: {
      kind: "image",
      src: thinking,
      width: 900,
      height: 400,
      alt: "Thoughts generated by the fine-tuned model, beginning: I wonder if I can keep up with myself.",
    },
  },
  "llm-grounding-mazegpt": {
    line: "GPT-3 and GPT-4 finding their way through a block maze from text descriptions of their surroundings.",
    thumb: { src: mazeThumb },
    glow: "#3cbd45",
    media: { kind: "youtube", id: "c6Bqb5Okdh8" },
  },
  s3synchrony: {
    line: "A Python package that keeps collaborators’ files in sync on an AWS S3 prefix.",
    thumb: { term: "pip install s3synchrony" },
    glow: "#3fb6c9",
    media: { kind: "code", text: "pip install s3synchrony" },
  },
  "dies-on-wafer": {
    line: "The most square dies that fit on a circular wafer, found by an iterative search that guarantees the best layout.",
    thumb: { src: diesThumb },
    glow: "#5b8cff",
    media: { kind: "youtube", id: "JXBoWL8pvEM" },
  },
};

/** Newest first, by when a project ended (or started, if it is still going). */
export const byRecent = <T extends { start: string; end?: string | null }>(a: T, b: T) =>
  String(b.end ?? b.start).localeCompare(String(a.end ?? a.start));
